spring:
  application:
    name: btgpactual-challange

  # Database
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://db:5432/orders_db
    username: manager
    password: pr03uc7s
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      database: postgresql

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  # Messaging
  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: guest
    password: guest
