spring:
  application:
    name: btgpactual-challange

  # Tools
  devtools:
    restart:
      poll-interval: 2s

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: manager
    password: pr03uc7s
    url: jdbc:postgresql://localhost:5432/orders_db
  jpa:
    show-sql: false
    hibernate:
      database: postgresql
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  # Messaging
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
