spring:
  application:
    name: btgpactual-challange
  datasource:
    driver-class-name: org.postgresql.Driver
    username: manager
    password: pr03uc7s
    url: jdbc:postgresql://localhost:5432/orders_db?stringtype=unspecified
  jpa:
    show-sql: true
    hibernate:
      database: postgresql
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  devtools:
    restart:
      poll-interval: 2s
