spring:
  application:
    name: btgpactual-challange

  # Tools
  devtools:
    restart:
      poll-interval: 2s

  # Database
  # PostgreSQL
  datasource:
    # PostgresSQL
    pg:
      url: jdbc:postgresql://localhost:5432/orders_db
      username: manager
      password: pr03uc7s
      driver-class-name: org.postgresql.Driver

    # H2
    h2:
      url: jdbc:postgresql://localhost:5432/orders_db
      username: manager
      password: pr03uc7s
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      database: postgresql

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  # Messaging
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
